### ISSUE TITLE
404 on cart remove

### ISSUE THREAD

**Issue by HoardingInfo** [derkkila/buttercup_store#9]
When clicking the "remove" button get 404 page.

<img width="619" alt="Screen Shot 2019-10-14 at 10 21 29 AM" src="https://user-images.githubusercontent.com/4707359/66766883-6df28600-ee6c-11e9-939c-de90c2f10a79.png">

**Comment by derkkila** [comment]
Just added the delete item method to the cart_microservice. Should be all set now once you update to the latest cart_microservice container.
